### ISSUE TITLE
Stable release?

### ISSUE THREAD

**Issue by matiit** [rappasoft/laravel-helpers#1]
Hey. I was just thinking about extracting same thing from laravel but found yours package. Thanks :)

I was just thinking whether it makes sense to mark it as stable so I don't need to add ```minimum-stability``` setting in ```composer.json```?

Laravel's version from which this code was extracted is stable anyway - so I don't think it will be a problem?

**Comment by rappasoft** [comment]
These are almost a year old, there are probably many more by now. But it may be easier for you to just add the file and include it in your 'files' array of composer.json: https://raw.githubusercontent.com/rappasoft/laravel-helpers/master/src/helpers.php

**Comment by matiit** [comment]
Probably you right, most simple solution is the best one.
Thanks for reply. 

You can close this "issue" :)

**Comment by rappasoft** [comment]
Glad it helps!
